#!/bin/bash -l

#$ -P cs585
#$ -m ea
#$ -N CS585_mse
#$ -j y
#$ -o resnet_mse.out
#$ -pe omp 4
#$ -l gpus=1
#$ -l gpu_c=6.0

### load your environment and run the job

# example:
module load miniconda
conda activate cs585
python submission.py
