#!/bin/bash -l

#$ -P cs585
#$ -m ea
#$ -N CS585_final_base
#$ -j y
#$ -o torch_base.out
#$ -pe omp 8
#$ -l gpus=1
#$ -l gpu_c=6.0

### load your environment and run the job

# example:
module load miniconda
conda activate cs585
python torch_base1.py
python torch_base2.py
python torch_base3.py
