#!/bin/bash -l

#$ -P cs585
#$ -m ea
#$ -N CS585_2v2
#$ -j y
#$ -o torch_base2v2.out
#$ -pe omp 8
#$ -l gpus=1
#$ -l gpu_c=6.0

### load your environment and run the job

# example:
module load miniconda
conda activate cs585
python torch_base2_v2.py
